apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../decoder-deployment.yaml
  - ../../coordinator-deployment.yaml
  - ../../decoder-pdb.yaml
  - ../../coordinator-pdb.yaml
  - ../../decoder-hpa.yaml
  - ../../coordinator-hpa.yaml
  - ../../monitoring-podmonitors.yaml
images:
  - name: universal-decoder
    newName: ghcr.io/code-with-zeeshan/universal-translation-system/decoder
    newTag: dev
  - name: universal-coordinator
    newName: ghcr.io/code-with-zeeshan/universal-translation-system/coordinator
    newTag: dev