# Root setup.py for UNIVERSAl TRANSLATION SYSTEM
from setuptools import setup, find_packages

setup(
    name='universal-translation-system',
    version='0.1.0',
    description='Universal Translation System: Edge encoding, cloud decoding, multi-platform SDKs',
    author='Mohammad Zeeshan',
    author_email='your.email@example.com',
    url='https://github.com/code-with-zeeshan/universal-translation-system',
    packages=find_packages(),
    install_requires=[
        'torch>=2.0.0',
        'transformers>=4.21.0,<5.0.0',
        'numpy>=1.21.0',
        'pandas>=2.0.0',
        'sentencepiece>=0.2.0',
        'tokenizers>=0.14.0',
        'sentence-transformers>=2.2.2',
        'sacrebleu>=2.3.0',
        'nltk>=3.8.0',
        'litserve>=0.2.0',
        'httpx>=0.25.0',
        'prometheus-client>=0.18.0',
        'psutil>=5.9.0',
        'msgpack>=1.0.0',
        'lz4>=4.3.2',
        'pyarrow>=14.0.0',
        'pytest>=7.4.0',
        'black>=23.10.0',
        'isort>=5.12.0',
        'mypy>=1.6.0',
        'pre-commit>=3.5.0',
        'scikit-learn>=1.3.0',
        'scipy>=1.11.0',
        'tqdm>=4.65.0',
        'pyyaml>=6.0.0',
        'jsonlines>=4.0.0',
        'requests>=2.31.0',
        'pathlib2>=2.3.7',
    ],
    python_requires='>=3.8',
    entry_points={
        'console_scripts': [
            'uts-train=scripts.train_from_scratch:main',
            'uts-build=scripts.build_models:main',
            # Add more CLI entry points as needed
        ],
    },
    include_package_data=True,
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
    ],
)
