version: '3.8'
services:
  encoder:
    build:
      context: ..
      dockerfile: docker/encoder.Dockerfile
    volumes:
      - ../models/encoder:/models/encoder
      - ../vocabulary:/vocabulary
    container_name: encoder_service
    restart: unless-stopped
    # Add ports or command as needed

  decoder:
    build:
      context: ..
      dockerfile: docker/decoder.Dockerfile
    volumes:
      - ../cloud_decoder:/app
      - ../models/decoder:/models/decoder
      - ../vocabulary:/vocabulary
    container_name: decoder_service
    restart: unless-stopped
    ports:
      - "8080:8080"  # Adjust as needed for your API
