# config/training_rtx3080.yaml

# RTX 3080-specific configuration (10GB/12GB memory, Ampere Architecture)
# Inherits from base.yaml. Memory is the primary constraint.

_base_: base.yaml

# All settings are under the 'training' key to correctly override the base config.
training:
  batch_size: 8
  accumulation_steps: 16 # Accumulate heavily to reach effective batch size.
  effective_batch_size: 128
  lr: 3e-4 # A stable learning rate for this class of GPU.
  gradient_checkpointing: true
  cpu_offload: true             # Offload optimizer state to CPU to save VRAM.
  activation_offload: false
  compile_mode: "reduce-overhead"
  dtype: "bfloat16"               # Ampere supports bfloat16.
  max_split_size: 128           # Smaller memory splits for less fragmentation.
  empty_cache_freq: 50          # Clean up memory more frequently.

distributed:
  gradient_as_bucket_view: false