# config/training_t4.yaml
# T4-specific configuration (16GB memory)
_base_: base.yaml

# T4 training settings - very limited memory
# All settings are under the 'training' key to correctly override the base config.
training:
  batch_size: 8
  accumulation_steps: 16
  effective_batch_size: 128
  lr: 2e-4  # Lower LR for stability
  gradient_checkpointing: true
  cpu_offload: true
  activation_offload: true
  compile_mode: "default"  # T4 might struggle with aggressive compilation
  dtype: "float16"
  max_split_size: 128  # Very small splits for 16GB memory
  empty_cache_freq: 50  # More frequent cleanup

distributed:
  gradient_as_bucket_view: false
  bucket_cap_mb: 10  # Smaller buckets