graph TB
    subgraph Cluster
        subgraph Ingress
            IG[HTTPS Ingress]
        end

        subgraph Services
            SCoord[coordinator svc]
            SDec[decoder svc]
            SMon[prometheus svc]
        end

        subgraph Deployments
            subgraph Coord
                C1[coordinator pod]
                C2[coordinator pod]
            end
            subgraph DecPool [Decoder Pool]
                D1[decoder pod GPU]
                D2[decoder pod GPU]
                DN[decoder pod N GPU]
            end
            subgraph Monitoring
                PR[prometheus pod]
                GR[grafana pod]
            end
        end
    end

    IG --> SCoord
    SCoord --> C1
    SCoord --> C2

    C1 --> SDec
    C2 --> SDec

    SDec --> D1
    SDec --> D2
    SDec --> DN

    C1 --> SMon
    C2 --> SMon
    D1 --> SMon
    D2 --> SMon
    DN --> SMon

    SMon --> PR
    PR --> GR
