# config/training_a100.yaml
# A100-specific configuration
# Inherits from base.yaml and overrides specific settings

# Load base configuration
_base_: base.yaml

# A100-specific training settings
training:
  # Override batch size and accumulation
  batch_size: 64
  accumulation_steps: 2
  effective_batch_size: 128

  # A100 can handle higher learning rates
  lr: 5e-4

  # A100 has enough memory - disable memory-saving features
  gradient_checkpointing: false
  cpu_offload: false
  activation_offload: false
  compile_mode: "max-autotune"  # A100 can handle aggressive optimization
  dtype: "bfloat16" # This is a memory setting, but part of TrainingConfig now

# A100 distributed settings
distributed:
  gradient_as_bucket_view: true
  static_graph: true