# config/training_v100.yaml
# V100-specific configuration
_base_: base.yaml

# V100-specific training settings
# All settings are under the 'training' key to correctly override the base config.
training:
  batch_size: 32
  accumulation_steps: 4
  effective_batch_size: 128
  lr: 3e-4
  gradient_checkpointing: true
  cpu_offload: false
  activation_offload: false
  compile_mode: "reduce-overhead"
  dtype: "float16"  # V100 doesn't support bfloat16 well

distributed:
  gradient_as_bucket_view: false