apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder-deployment
  labels:
    app: decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
      - name: decoder
        image: universal-decoder:latest
        command: ["litserve", "serve", "optimized_decoder:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "4"
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "8"
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: OMP_NUM_THREADS
          value: "4"
        - name: MODEL_PATH
          value: "/app/models/decoder_model.pt"
        - name: VOCAB_DIR
          value: "/app/vocabs"
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_BATCH_SIZE
          value: "64"
        - name: BATCH_TIMEOUT_MS
          value: "10"
        - name: DECODER_JWT_SECRET_FILE
          value: "/var/run/secrets/uts/decoder-jwt-secret"
        - name: JWT_PRIVATE_KEY_FILE
          value: "/var/run/secrets/uts/jwt-private-key"
        - name: JWT_PUBLIC_KEY_PATH
          value: "/var/run/secrets/uts/jwt-public-key"
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: vocabs
          mountPath: /app/vocabs
        - name: uts-secrets
          mountPath: /var/run/secrets/uts
          readOnly: true
      volumes:
      - name: models
        persistentVolumeClaim:
          # This PVC should be created separately and point to your model storage
          claimName: model-storage-pvc
      - name: vocabs
        persistentVolumeClaim:
          # This PVC should point to your vocabulary storage
          claimName: vocab-storage-pvc
      - name: uts-secrets
        secret:
          secretName: translation-system-secrets
          items:
          - key: decoder-jwt-secret
            path: decoder-jwt-secret
          - key: jwt-private-key
            path: jwt-private-key
          - key: jwt-public-key
            path: jwt-public-key
      nodeSelector:
        kubernetes.io/hostname: gpu-node
