apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: encoder-artifacts-pvc
  namespace: translation-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 