apiVersion: v1
kind: Secret
metadata:
  name: translation-system-secrets
  namespace: uts
type: Opaque
data:
  # base64-encoded values; replace with your own
  coordinator-secret: REPLACE_WITH_YOUR_OWN_SECRET_HERE
  coordinator-jwt-secret: REPLACE_WITH_YOUR_OWN_SECRET_HERE
  coordinator-token: REPLACE_WITH_YOUR_OWN_SECRET_HERE
  internal-service-token: REPLACE_WITH_YOUR_OWN_SECRET_HERE
  decoder-jwt-secret: REPLACE_WITH_YOUR_OWN_SECRET_HERE
  # Optional RS256 keys (PEM)
  jwt-private-key: REPLACE_WITH_BASE64_PEM
  jwt-public-key: REPLACE_WITH_BASE64_PEM