"""
Translation quality utilities — minimal inference-time helpers.
The model learns idioms, false friends, and cultural context from training data
(generated by data/synthetic_augmentation.py). Only tone/register hints
(user intent signals that cannot be learned) and basic grammar regex remain here.
"""
import logging
import re
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ── Tone/Register Control ──────────────────────────────────────────────
# These are user intent signals at inference time — cannot be learned from data.

TONE_TAGS = {"FORMAL", "CASUAL", "NEUTRAL"}

TONE_PROMPTS: Dict[str, Dict[str, str]] = {
    "FORMAL": {
        "en": " [Formal register: use polite forms, avoid contractions, use full sentences]",
        "es": " [Registro formal: use usted, evite contracciones, oraciones completas]",
        "fr": " [Registre soutenu: utilisez vous, évitez les contractions, phrases complètes]",
        "de": " [Formelles Register: verwenden Sie Sie, keine Kontraktionen, vollständige Sätze]",
        "pt": " [Registro formal: use você, evite contrações, frases completas]",
        "it": " [Registro formale: usi Lei, eviti contrazioni, frasi complete]",
        "ja": " [敬体: ですます調を使用し、丁寧な表現]",
        "zh": " [正式语体: 使用礼貌用语，完整句子]",
        "ru": " [Официальный стиль: используйте Вы, полные предложения]",
        "ar": " [السجل الرسمي: استخدم صيغ المهذبة والجمل الكاملة]",
        "ko": " [격식체: 존댓말 사용, 완전한 문장]",
        "nl": " [Formeel register: gebruik u, vermijd samentrekkingen]",
        "pl": " [Oficjalny styl: używaj Pan/Pani, pełne zdania]",
        "tr": " [Resmi kayıt: nazlı ifadeler kullanın, tam cümleler]",
        "th": " [ทางการ: ใช้คำสุภาพ ประโยคสมบูรณ์]",
        "vi": " [Trang trọng: dùng kính ngữ, câu đầy đủ]",
        "hi": " [औपचारिक: आदरसूचक शब्दों का प्रयोग करें]",
        "sv": " [Formellt register: använd ni, fullständiga meningar]",
        "uk": " [Офіційний стиль: використовуйте Ви, повні речення]",
        "id": " [Formal: gunakan kata sopan, kalimat lengkap]",
    },
    "CASUAL": {
        "en": " [Casual register: use everyday language, contractions OK, conversational]",
        "es": " [Registro casual: lenguaje cotidiano, tuteo, conversacional]",
        "fr": " [Registre familier: langage quotidien, tutoiement]",
        "de": " [Umgangssprache: duzen, Alltagssprache]",
        "pt": " [Registro casual: linguagem do dia a dia, tratamento informal]",
        "it": " [Registro informale: dai del tu, linguaggio quotidiano]",
        "ja": " [カジュアル: 日常的な表現、くだけた言い方]",
        "zh": " [非正式语体: 日常用语，随意表达]",
        "ru": " [Неформальный стиль: повседневный язык]",
        "ar": " [غير رسمي: لغة يومية]",
        "ko": " [비격식체: 일상적인 표현, 반말]",
        "nl": " [Informeel register: dagelijkse taal]",
        "pl": " [Nieformalny styl: język potoczny]",
        "tr": " [Gayriresmi: günlük dil, samimi ifadeler]",
        "th": " [ไม่เป็นทางการ: ภาษาพูดในชีวิตประจำวัน]",
        "vi": " [Thân mật: ngôn ngữ hàng ngày]",
        "hi": " [अनौपचारिक: रोज़मर्रा की भाषा]",
        "sv": " [Informellt register: vardagsspråk]",
        "uk": " [Неформальний стиль: повсякденна мова]",
        "id": " [Kasual: bahasa sehari-hari, santai]",
    },
}

FRIENDLY_TIE_BREAKER: Dict[str, str] = {
    lang: " [Natural, idiomatic, meaning-first translation]" for lang in (
        "en", "es", "fr", "de", "pt", "it", "ja", "zh", "ru",
        "ar", "ko", "nl", "pl", "tr", "th", "vi", "hi", "sv", "uk", "id"
    )
}


def detect_tone(text: str) -> str:
    """Detect register from explicit prefix tag ([FORMAL], [CASUAL], [NEUTRAL])."""
    text_stripped = text.strip().upper()
    for tag in TONE_TAGS:
        if text_stripped.startswith(f"[{tag}]"):
            return tag
    if text_stripped.startswith("[") and "]" in text_stripped[:20]:
        return "NEUTRAL"
    return "NEUTRAL"


def strip_tone_tag(text: str) -> str:
    """Remove tone tag prefix from text."""
    text_stripped = text.strip().upper()
    for tag in TONE_TAGS:
        marker = f"[{tag}]"
        if text_stripped.startswith(marker):
            return text[len(marker):].strip()
    return text


def apply_tone_prompt(text: str, tone: str, lang: str) -> str:
    """Append a tone/register hint to the source text to guide the decoder."""
    if tone == "NEUTRAL":
        return text
    prompts = TONE_PROMPTS.get(tone, {})
    hint = prompts.get(lang, prompts.get("en", ""))
    if hint:
        return text + hint
    return text


# ── Grammar Post-Processing ────────────────────────────────────────────
# Minimal regex safety net for common output issues.


def postprocess_grammar(text: str, lang: str) -> str:
    """Apply basic language-specific grammar fixes."""
    if lang == "en":
        text = re.sub(r'\bi\b', 'I', text)
        text = re.sub(r"' ([A-Za-z])", r"'\1", text)
    elif lang == "fr":
        text = re.sub(r'\bl\s+\'', "l'", text)
        text = re.sub(r'\bd\s+\'', "d'", text)
        text = re.sub(r'(\w)\s+-\s+(\w)', r'\1-\2', text)
    elif lang == "de":
        if text and text[0].islower() and not text.startswith(("kein", "mein", "sein", "ein")):
            text = text[0].upper() + text[1:]
    elif lang in ("es", "it", "pt"):
        text = re.sub(
            r'\b(\w+)lo\s+(\w+)\b',
            lambda m: m.group(1) + "lo " + m.group(2)
            if m.group(1).endswith(("r", "s"))
            else m.group(0),
            text,
        )
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r'\s([?.!,"])', r'\1', text)
    text = re.sub(r'(["\']) ', r'\1', text)
    return text


# ── Quality Scoring ────────────────────────────────────────────────────
# Model-agnostic metrics for beam reranking and evaluation.


def score_translation_quality(
    source_text: str,
    translation: str,
    source_lang: str,
    target_lang: str,
    log_probs: Optional[List[float]] = None,
) -> Dict[str, float]:
    """Score translation on length ratio, perplexity, and diversity.

    Args:
        source_text: Original source text
        translation: Generated translation
        source_lang: Source language code (unused, for API compatibility)
        target_lang: Target language code (unused, for API compatibility)
        log_probs: Per-token log probabilities from decoder (if available)

    Returns:
        Dict of quality scores (0-1 scale, higher is better)
    """
    scores = {}

    src_len = len(source_text.split())
    tgt_len = len(translation.split())
    if src_len > 0 and tgt_len > 0:
        ratio = tgt_len / src_len
        if 0.5 <= ratio <= 2.0:
            scores["length_score"] = 1.0 - abs(1.0 - ratio) / 1.5
        else:
            scores["length_score"] = 0.1
    else:
        scores["length_score"] = 0.0

    if log_probs and len(log_probs) > 0:
        avg_log_prob = sum(log_probs) / len(log_probs)
        perplexity = 2.0 ** (-avg_log_prob)
        scores["perplexity"] = max(0.0, min(1.0, 1.0 - (perplexity / 100.0)))
    else:
        scores["perplexity"] = 0.5

    words = translation.lower().split()
    if len(words) > 3:
        unique_ratio = len(set(words)) / len(words)
        scores["diversity"] = min(1.0, unique_ratio * 1.5)
    else:
        scores["diversity"] = 1.0

    score_keys = [k for k in scores if k != "overall"]
    scores["overall"] = sum(scores[k] for k in score_keys) / max(len(score_keys), 1)
    return scores


# ── Inference Pipeline ─────────────────────────────────────────────────


class TranslationQualityPipeline:
    """Inference-time pipeline: tone tagging, grammar post-processing, beam reranking.

    The model handles idioms, false friends, and cultural context from training
    data. This pipeline only provides user intent signals (tone tags) and a
    lightweight grammar safety net.
    """

    def __init__(self, grammar_postprocess: bool = True):
        self.grammar_postprocess = grammar_postprocess

    def prepare_input(
        self,
        text: str,
        source_lang: str,
        target_lang: str,
        domain: Optional[str] = None,
    ) -> Tuple[str, str, str]:
        """Detect tone tag and append register prompt.

        Returns:
            (processed_text, tone, domain)
        """
        tone = detect_tone(text)
        cleaned = strip_tone_tag(text)
        text_with_hints = apply_tone_prompt(cleaned, tone, source_lang)
        if tone == "NEUTRAL":
            text_with_hints = cleaned + FRIENDLY_TIE_BREAKER.get(source_lang, "")
        return text_with_hints, tone, domain or "general"

    def postprocess(self, translation: str, target_lang: str, tone: str) -> str:
        """Post-process translation output."""
        if self.grammar_postprocess:
            translation = postprocess_grammar(translation, target_lang)
        return translation

    def rerank_candidates(
        self,
        source_text: str,
        candidates: List[Tuple[str, Optional[List[float]]]],
        source_lang: str,
        target_lang: str,
    ) -> str:
        """Select best candidate by quality score."""
        if len(candidates) <= 1:
            return candidates[0][0] if candidates else ""

        scored = [
            (score_translation_quality(source_text, t, source_lang, target_lang, lp).get("overall", 0.5), t)
            for t, lp in candidates
        ]
        scored.sort(key=lambda x: x[0], reverse=True)
        return scored[0][1]
