apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uts.fullname" . }}-coordinator
  labels:
    app.kubernetes.io/name: {{ include "uts.name" . }}-coordinator
    helm.sh/chart: {{ include "uts.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  coordinator-jwt-secret: {{ .Values.coordinator.secret.jwtSecret | quote }}
  coordinator-secret: {{ .Values.coordinator.secret.secret | quote }}
  coordinator-token: {{ .Values.coordinator.secret.token | quote }}
  internal-service-token: {{ .Values.coordinator.secret.internalServiceToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uts.fullname" . }}-decoder
  labels:
    app.kubernetes.io/name: {{ include "uts.name" . }}-decoder
    helm.sh/chart: {{ include "uts.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  decoder-jwt-secret: {{ .Values.decoder.secret.jwtSecret | quote }}
---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uts.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "uts.name" . }}-redis
    helm.sh/chart: {{ include "uts.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.secret.password | quote }}
{{- end }}
