name: Enforce Branch Protection Rules

on:
  workflow_dispatch: # Manual trigger only

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch protection rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [], // Empty for now, add as you create workflows
              },
              enforce_admins: false, // Set to false so you can push fixes
              required_pull_request_reviews: null, // Disable for solo project
              restrictions: null,
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: false,
              required_signatures: false // Disable until you set up GPG
            });