name: Docker Build PR Images

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: pr-docker-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build-and-push:
    # Only push images for PRs from the same repository (not forks) for security
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR tags
        id: vars
        run: |
          echo "prtag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          echo "shatag=pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Build & push encoder (PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/encoder.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/encoder:${{ steps.vars.outputs.prtag }}
            ghcr.io/${{ github.repository }}/encoder:${{ steps.vars.outputs.shatag }}

      - name: Build & push decoder (PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/decoder.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/decoder:${{ steps.vars.outputs.prtag }}
            ghcr.io/${{ github.repository }}/decoder:${{ steps.vars.outputs.shatag }}

      - name: Build & push coordinator (PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/coordinator.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/coordinator:${{ steps.vars.outputs.prtag }}
            ghcr.io/${{ github.repository }}/coordinator:${{ steps.vars.outputs.shatag }}