name: Docker Build & Push

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: vars
        run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & push encoder
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/encoder.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/encoder:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}/encoder:latest

      - name: Build & push decoder
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/decoder.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/decoder:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}/decoder:latest

      - name: Build & push coordinator
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/coordinator.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/coordinator:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository }}/coordinator:latest