name: Helm Lint

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.4'
      - name: Lint chart
        run: |
          helm lint charts/uts