name: Kustomize Deploy (example)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.0.2)"
        required: true

jobs:
  build-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize
        run: |
          curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          sudo mv kustomize /usr/local/bin/

      - name: Patch images with input version
        working-directory: kubernetes/overlays
        run: |
          sed -i "s/newTag: .*/newTag: ${GITHUB_INPUT_VERSION}/g" kustomization.yaml || true
        env:
          GITHUB_INPUT_VERSION: ${{ github.event.inputs.version }}

      - name: Build manifests
        working-directory: kubernetes/overlays
        run: |
          kustomize build . > ../../manifests.out.yaml
          echo "Built manifests:" && head -n 50 ../../manifests.out.yaml