name: Mobile SDK Tests

on:
  push:
    paths:
      - 'android/**'
      - 'ios/**'
  pull_request:
    paths:
      - 'android/**'
      - 'ios/**'

jobs:
  android-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test Android SDK
      run: |
        cd android/UniversalTranslationSDK
        ./gradlew test

  ios-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test iOS SDK
      run: |
        cd ios/UniversalTranslationSDK
        swift test