name: Mobile SDK Tests

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'android/**'
      - 'ios/**'
      - 'react-native/**'
      - 'web/**'
      - 'flutter/**'

jobs:
  android-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test Android SDK
      run: |
        cd android/UniversalTranslationSDK
        ./gradlew test


  ios-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test iOS SDK
      run: |
        cd ios/UniversalTranslationSDK
        swift test


  react-native-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd react-native/UniversalTranslationSDK
        npm install
    - name: Test React Native SDK
      run: |
        cd react-native/UniversalTranslationSDK
        npm test

  web-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd web/universal-translation-sdk
        npm install
    - name: Test Web SDK
      run: |
        cd web/universal-translation-sdk
        npm test

  integration-test:
    runs-on: ubuntu-latest
    needs: [android-test, ios-test, react-native-test, web-test]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run integration tests
      run: |
        pytest tests/test_complete_integration.py -v