name: Publish Python Package (decoder-node)

on:
  push:
    branches: [ main ]
    paths:
      - 'universal-decoder-node/**'
      - '.github/workflows/publish-python.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build wheel and sdist
        working-directory: universal-decoder-node
        run: |
          python -m build

      - name: Publish to PyPI on tag
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --non-interactive --skip-existing universal-decoder-node/dist/*