name: Release Please (core + python)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          package-name: universal-translation-system
          changelog-types: |
            [{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance"},{"type":"chore","section":"Chores","hidden":false},{"type":"refactor","section":"Refactors"}]
      - name: Output
        run: |
          echo "release_created=${{ steps.release.outputs.release_created }}"
      - name: Create tag when release PR merged
        if: steps.release.outputs.release_created == 'true'
        run: echo 'Tag will be created by release-please on merge'