name: Scheduled Secret Rotation (Example)

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 03:00 UTC
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography

      - name: Rotate HS256 coordinator/decoder secrets (example)
        env:
          # In real usage, write to an external secret manager; here, this is illustrative only.
          UTS_CREDMGR_USE_KEYRING: "false"
        run: |
          python tools/rotate_secrets.py --type hs256 --key coordinator_jwt_secret
          python tools/rotate_secrets.py --type hs256 --key decoder_jwt_secret

      - name: Generate RS256 pair (preview)
        run: |
          python tools/rotate_secrets.py --type rs256 --kid weekly-$(date +%Y%m%d) --set-env

      - name: Guidance
        run: |
          echo "Review rotation outputs and update your external secret store (vault/KMS/GH Actions secrets)."
          echo "Then roll out by redeploying services or triggering environment refresh."