name: Secret Scan (Gitleaks)

on:
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
      - '.github/ISSUE_TEMPLATE/**'
  schedule:
    - cron: '0 2 * * 1'  # weekly scan on Monday 02:00 UTC

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for gitleaks to scan history/changes correctly

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --verbose --redact