name: Secret Hygiene

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.py'
      - '**/*.env'
      - '.env.example'
      - '.github/scripts/secret_hygiene_check.py'
      - '.github/workflows/secret-hygiene.yml'

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run secret hygiene check
        run: |
          python .github/scripts/secret_hygiene_check.py