name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for gitleaks to scan history/changes correctly

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --verbose --redact