name: Security Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'coordinator/**'
      - 'utils/**'
      - 'tests/test_security.py'
      - 'tests/test_revocation.py'
      - '.github/workflows/security-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'coordinator/**'
      - 'utils/**'
      - 'tests/test_security.py'
      - 'tests/test_revocation.py'
      - '.github/workflows/security-tests.yml'

jobs:
  run-security-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
    
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run security tests
      env:
        # Avoid network in tests; provide minimal envs
        COORDINATOR_SECRET: 'this-is-a-temporary-test-secret-aaaaaaaaaaaaaaaaaaaa'
        COORDINATOR_JWT_SECRET: 'this-is-a-temporary-test-jwt-secret-aaaaaaaaaaaa'
        COORDINATOR_TOKEN: 'this-is-a-temporary-test-token-aaaaaaaaaaaaaaaaaaaaa'
        INTERNAL_SERVICE_TOKEN: 'this-is-a-temporary-internal-token-aaaaaaaaaaaaa'
      run: |
        pytest -v tests/test_security.py tests/test_revocation.py