# cloud_decoder/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'universal_decoder'
    static_configs:
      - targets: ['decoder:8000']
    metrics_path: '/metrics'

  - job_name: 'system_metrics'
    static_configs:
      - targets: ['localhost:9000']
  
  # Optional: separate vocabulary monitoring
  - job_name: 'vocabulary_metrics'
    static_configs:
      - targets: ['localhost:9001']  