# cloud_decoder/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'universal_decoder'
    static_configs:
      - targets: ['decoder:8000']
    metrics_path: '/metrics'